import sys

ARG_ERROR = (10, "INVALID ARGUMENTS.")
FILE_ERROR = (11, "FILLE DOES NOT EXISTS OR CANNOT BE READ FROM.")
XML_FORMAT_ERROR = (31, "XML IS MALFORMED.")
XML_STRUCT_ERROR = (32, "XML CONTAINS UNEXPECTED STRUCTURE.")
ASSERT_TAG_ERROR = (32, "XML ASSERT TAG ERROR.")
ASSERT_ATTR_ERROR = (32, "XML ASSERT ATTR ERROR.")
ASSERT_VALUE_ERROR = (32, "XML ASSERT VALUE ERROR.")
ASSERT_OPCODE_VALUE_ERROR = (32, "XML ASSERT OPCODE FORMAT ERROR.")
ASSERT_ARG_COUNT_ERROR = (32, "XML ARGUMENT COUNT ERROR.")
ASSERT_ORDER_TYPE_ERROR = (32, "XML TYPE OF ORDER VALUE IS NOT INT ERROR.")
ASSERT_ORDER_VALUE_ERROR = (32, "XML ORDER VALUE IS DUPLICITE OR NEGATIVE.")


ASSERT_TYPE_ERROR = (53, "XML TYPE ERROR.")
ASSERT_SAME_TYPE_ERROR = (53, "XML SAME TYPE ERROR.")


def exit_and_print(exittuple):
    print("ERROR: "+exittuple[1], file=sys.stderr)
    exit(exittuple[0])
