import sys

ARG_ERROR = (10, "INVALID ARGUMENTS.")
FILE_ERROR = (11, "FILLE DOES NOT EXISTS OR CANNOT BE READ FROM.")
XML_FORMAT_ERROR = (31, "XML IS MALFORMED.")
XML_STRUCT_ERROR = (32, "XML CONTAINS UNEXPECTED STRUCTURE.")
ASSERT_TAG_ERROR = (32, "XML ASSERT TAG ERROR.")
ASSERT_ATTR_ERROR = (32, "XML ASSERT ATTR ERROR.")
ASSERT_VALUE_ERROR = (32, "XML ASSERT VALUE ERROR.")
ASSERT_OPCODE_VALUE_ERROR = (32, "XML ASSERT OPCODE FORMAT ERROR.")
ASSERT_ARG_COUNT_ERROR = (32, "XML ARGUMENT COUNT ERROR.")
ASSERT_ORDER_TYPE_ERROR = (32, "XML TYPE OF ORDER VALUE IS NOT INT ERROR.")
ASSERT_ORDER_VALUE_ERROR = (32, "XML ORDER VALUE IS DUPLICITE OR NEGATIVE.")
ASSERT_TYPE_DOESNT_MATCH_VALUE_ERROR = (32, "XML TYPE DOESNT MATCH VALUE.")
INTERNAL_ERROR = (99, "INTERNAL ERROR.")


ASSERT_TYPE_ERROR = (53, "XML TYPE ERROR.")
ASSERT_SAME_TYPE_ERROR = (53, "XML SAME TYPE ERROR.")

SEMANTIC_VAR_ALREADY_EXISTS = (52, "SEMANTIC VARIABLE ALREADY EXISTS ERROR.")
SEMANTIC_WRONG_OPERAND_TYPE = (53, "SEMANTIC WRONG OPERAND TYPE ERROR.")
SEMANTIC_VAR_DOES_NOT_EXISTS = (54, "SEMANTIC VARIABLE DOES NOT EXISTS ERROR.")
SEMANTIC_DIVISION_BY_ZERO = (57, "SEMANTIC DIVISION BY ZERO ERROR.")
SEMANTIC_FRAME_DOES_NOT_EXIST = (55, "SEMANTIC FRAME DOES NOT EXIST ERROR.")


def exit_and_print(exittuple):
    print("ERROR: "+exittuple[1], file=sys.stderr)
    exit(exittuple[0])
